### PR TITLE
Add immediate feedback sound when adjusting alert volume  ( Closes #17 )

### LINKED ISSUE #17: Play alert sound preview when changing volume of alert sound
At the moment, a user is unable to gauge how loud the alert sound(s) will be until they actually play at the end of a timer. The alarm sound should play every time the alert volume is changed to give the user an idea of how loud the alert will be.

### PR DESCRIPTION
**Pull request by RameezIbrahimOfficial**
- Integrated WORK_SOUND to play every time the volume is changed.
- Updated setVolume function to play the sound immediately after the volume adjustment.
Closes #17

### CODE REVIEW

**Comment by nicholasdly** [comment]
> Hi @nicholasdly , will it automatically Merge or do you need to approve it.

I will approve of the PR after I've reviewed it and functions as expected in the preview deployment.

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly OK

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly Any updates ?

**Comment by nicholasdly** [comment]
> @nicholasdly Any updates ?

@RameezIbrahimOfficial You have not pushed any changes that resolve my comments.

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly which comment are you talking about.
the issue #17 is resolved in this PR.

is there anything else need to do.

**Comment by nicholasdly** [comment]
@RameezIbrahimOfficial I left comments directly on your pull request as a review. You should be able to see them by scrolling up, or clicking on the "Files changed" tab.

Screenshot 2024-10-14 at 9 05 24 AM

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly 
for WORK_SOUND also set the sound.

**Comment by nicholasdly** [comment]
@RameezIbrahimOfficial Thanks! There was still a very small change to be made that I left in that review comment, so I just took over in a separate PR—see #26.

**Comment by RameezIbrahimOfficial** [comment]
@nicholasdly I am not able to see the comments that's the issue .

**Pull request closed without merging**
